name: nurbanhoney
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  authentication_service:
    path: application/authentication_service
  authentication_domain:
    path: domain/authentication_domain
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12
  flutter_material_pickers: ^3.6.0
  flutter_riverpod: ^2.0.2
  cupertino_icons: ^1.0.2
  navigation_domain:
    path: domain/navigation_domain
  navigation_service:
    path: application/navigation_service
  nurbanhoney_ui_service:
    path: application/nurbanhoney_ui_service
  preference_storage_service:
    path: application/preference_storage_service
  preference_storage:
    path: data/preference_storage
  dio: ^5.7.0
  dio_domain:
    path: domain/dio_domain
  dio_service:
    path: application/dio_service
  dio_repository:
    path: data/dio_repository
  share_service:
    path: application/share_service
  kakao_flutter_sdk: ^1.9.6
  kakao_flutter_sdk_user: ^1.9.6
  cached_network_image: ^3.2.3
  image_picker: ^1.0.4
  uuid: ^4.0.0
  google_mobile_ads: ^6.0.0
  android_id: ^0.4.0
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  json_serializable: ^6.8.0
  http: ^1.2.2
  retrofit: ^4.4.1
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/splash/
    - assets/images/home/
    - assets/images/login/
    - assets/images/article_detail/
    - assets/images/article_create/
    - assets/images/myaccount/
    - assets/images/common/

flutter_gen:
  line_length: 80
  assets:
    output:
      package_parameter_enabled: true